name: Hackerrank Tests

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Enter Cucumber tag to run (e.g., @TC_1)"
        required: true
        default: "@TC_1"

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests with tag
        run: npx cucumber-js --tags "${{ github.event.inputs.tag }}"

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/
